spring:
  datasource:
    # for test(non hikari)
    url: jdbc:mariadb://localhost:12001/AUTH
    username: root
    password: msa-maria-db
    hikari:
      jdbc-url: jdbc:mariadb://localhost:12001/AUTH
      username: root
      password: msa-maria-db
  data:
    redis:
      host: localhost
      port: 12002
      username: default
      password: msa_redis
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging.level:
  org.hibernate:
    orm.jdbc.bind : trace
    engine.jdbc.batch.internal.BatchingBatch: trace
