### request to berry throw with gateway
GET http://localhost:8100/gates/berries/taken
Content-Type: application/json

""


### request to nut throw with gateway
GET http://localhost:8100/gates/nuts/taken
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtc2Ffc3ViamVjdCIsImlhdCI6MTcyNDg1MTAzNywiZXhwIjoxNzU2Mzg3MDM3LCJ0eXBlIjoiRElSRUNUIn0.AJ2_Km9wQrvgRZDAZ3rCDIQqcgxTPLARKgzZJzZZAhgvHCOobE3SCuG0v6XfwIwd13P3obw-a3jX_EaK2X-gzQ


""

### register
POST http://localhost:{{authport}}/auth/register
Content-Type: application/json

{
  "userId": "chunbok",
  "password": "chunbok"
}

### login
POST http://localhost:{{authport}}/auth/login
Content-Type: application/json

{
  "userId": "chunbok",
  "password": "chunbok"
}

### user out
DELETE http://localhost:{{authport}}/auth/user
Content-Type: application/json

{
  "userId": "chunbok3"
}

### role register
PUT http://localhost:{{authport}}/auth/role
Content-Type: application/json

{
  "service": "BERRIES",
  "contact": "OPEN",
  "description": "Open api contact role for Berries service"
}

### role assign
POST http://localhost:9300/auth/assign_role
Content-Type: application/json

{
  "userNo": 1,
  "roles": [
    {
      "service" : "NUTS",
      "contact": "OPEN"
    }
  ]
}